if (!isServer) exitWith {};

waitUntil {!isNil "ALiVE_STATIC_DATA_LOADED"};

ALIVE_factionDefaultTransport = [] call ALIVE_fnc_hashCreate;
[ALIVE_factionDefaultTransport, "STAF_PMC", ["STAF_truck_transport","STAF_offroad","STAF_offroad_pickup","STAF_suv"]] call ALIVE_fnc_hashSet;

ALIVE_factionDefaultAirTransport = [] call ALIVE_fnc_hashCreate;
[ALIVE_factionDefaultAirTransport, "STAF_PMC", [""]] call ALIVE_fnc_hashSet;

ALIVE_factionDefaultSupports = [] call ALIVE_fnc_hashCreate;
[ALIVE_factionDefaultSupports, "STAF_PMC", ["STAF_truck_transport","STAF_offroad","STAF_offroad_pickup","STAF_suv"]] call ALIVE_fnc_hashSet;

ALIVE_factionDefaultSupplies = [] call ALIVE_fnc_hashCreate;
[ALIVE_factionDefaultSupplies, "STAF_PMC", [""]] call ALIVE_fnc_hashSet;

ALIVE_autoGeneratedTasks = ["CivAssault","Assassination","DestroyVehicles","DestroyInfantry","InsurgencyPatrol","InsurgencyDestroyAssets","Rescue","CaptureObjective"];
