removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;

player forceAddUniform "IP_U_B_CombatUniform_Splinter_Altis";
for "_i" from 1 to 4 do {player addItemToUniform "30Rnd_65x39_caseless_mag";};
player addVest "IP_V_PlateCarrier1_rgrEF";
player addItemToVest "muzzle_snds_H";
player addItemToVest "muzzle_snds_acp";
player addItemToVest "ACE_personalAidKit";
for "_i" from 1 to 2 do {player addItemToVest "ACE_packingBandage";};
player addItemToVest "ACE_tourniquet";
player addItemToVest "ACE_morphine";
for "_i" from 1 to 2 do {player addItemToVest "ACE_elasticBandage";};
player addItemToVest "ACE_EarPlugs";
player addItemToVest "ACE_IR_Strobe_Item";
player addItemToVest "11Rnd_45ACP_Mag";
for "_i" from 1 to 8 do {player addItemToVest "30Rnd_65x39_caseless_mag";};
for "_i" from 1 to 2 do {player addItemToVest "SmokeShell";};
player addItemToVest "HandGrenade";
player addBackpack "B_Kitbag_rgr";
player addItemToBackpack "ACE_M26_Clacker";
player addItemToBackpack "ACE_DefusalKit";
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_M14";};
for "_i" from 1 to 2 do {player addItemToBackpack "DemoCharge_Remote_Mag";};
for "_i" from 1 to 2 do {player addItemToBackpack "SatchelCharge_Remote_Mag";};
for "_i" from 1 to 2 do {player addItemToBackpack "APERSBoundingMine_Range_Mag";};
player addItemToBackpack "ClaymoreDirectionalMine_Remote_Mag";
player addHeadgear "IP_H_HelmetSpecB_Green";

player addWeapon "IP_arifle_MX_Sage_F";
player addPrimaryWeaponItem "acc_pointer_IR";
player addPrimaryWeaponItem "optic_Hamr";
player addWeapon "hgun_Pistol_heavy_01_F";

player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "tf_rf7800str_2";
player linkItem "ItemAndroid";
player linkItem "NVGoggles_INDEP";
