comment "Exported from Arsenal by IndeedPete";

comment "Remove existing items";
removeAllWeapons _this;
removeAllItems _this;
removeAllAssignedItems _this;
removeUniform _this;
removeVest _this;
removeBackpack _this;
removeHeadgear _this;
removeGoggles _this;

comment "Add containers";
_this forceAddUniform "STAF_U_BG_Guerilla1_1_Flecktarn_Norwegian";
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_morphine";};
_this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_CableTie";};
_this addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_IR_Strobe_Item";};
_this addItemToUniform "9Rnd_45ACP_Mag";
_this addVest "V_HarnessO_brn";
_this addItemToVest "Chemlight_red";
_this addItemToVest "Chemlight_yellow";
_this addItemToVest "Chemlight_blue";
_this addItemToVest "SmokeShell";
_this addItemToVest "SmokeShellYellow";
_this addItemToVest "SmokeShellRed";
_this addItemToVest "SmokeShellGreen";
_this addItemToVest "SmokeShellPurple";
_this addItemToVest "SmokeShellBlue";
_this addItemToVest "SmokeShellOrange";
_this addItemToVest "Chemlight_green";
_this addItemToVest "9Rnd_45ACP_Mag";
_this addItemToVest "200Rnd_65x39_cased_Box_Tracer";
_this addItemToVest "200Rnd_65x39_cased_Box_Tracer";
_this addBackpack "B_FieldPack_blk";
for "_i" from 1 to 4 do {_this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 3 do {_this addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 3 do {_this addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 2 do {_this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 3 do {_this addItemToBackpack "ACE_quikclot";};
_this addItemToBackpack "ACE_NVG_Gen2";
_this addItemToBackpack "acc_pointer_IR";
_this addItemToBackpack "muzzle_snds_acp";
_this addItemToBackpack "muzzle_snds_H_MG";
for "_i" from 1 to 2 do {_this addItemToBackpack "MiniGrenade";};
for "_i" from 1 to 2 do {_this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 2 do {_this addItemToBackpack "200Rnd_65x39_cased_Box_Tracer";};
for "_i" from 1 to 2 do {_this addItemToBackpack "HandGrenade";};
_this addHeadgear "H_Bandanna_camo";
_this addGoggles "G_Bandanna_beast";

comment "Add weapons";
_this addWeapon "LMG_Mk200_F";
_this addPrimaryWeaponItem "acc_flashlight";
_this addPrimaryWeaponItem "optic_Arco";
_this addPrimaryWeaponItem "bipod_02_F_tan";
_this addWeapon "hgun_ACPC2_F";
_this addWeapon "Binocular";
_this addMagazine "200Rnd_65x39_cased_Box_Tracer";

comment "Add items";
_this linkItem "ItemMap";
_this linkItem "ItemCompass";
_this linkItem "ItemWatch";
_this linkItem "ItemAndroid";
