comment "Exported from Arsenal by IndeedPete";

comment "Remove existing items";
removeAllWeapons _this;
removeAllItems _this;
removeAllAssignedItems _this;
removeUniform _this;
removeVest _this;
removeBackpack _this;
removeHeadgear _this;
removeGoggles _this;

comment "Add containers";
_this forceAddUniform "U_BG_Guerrilla_6_1";
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_morphine";};
_this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_CableTie";};
_this addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_IR_Strobe_Item";};
_this addItemToUniform "16Rnd_9x21_Mag";
_this addVest "V_Chestrig_rgr";
_this addItemToVest "ACE_Clacker";
_this addItemToVest "ACE_M26_Clacker";
_this addItemToVest "ACE_DefusalKit";
_this addItemToVest "ACE_DeadManSwitch";
_this addItemToVest "Chemlight_red";
_this addItemToVest "Chemlight_yellow";
_this addItemToVest "Chemlight_blue";
_this addItemToVest "SmokeShell";
_this addItemToVest "SmokeShellYellow";
_this addItemToVest "SmokeShellRed";
_this addItemToVest "SmokeShellGreen";
_this addItemToVest "SmokeShellPurple";
_this addItemToVest "SmokeShellBlue";
_this addItemToVest "SmokeShellOrange";
_this addItemToVest "Chemlight_green";
_this addItemToVest "16Rnd_9x21_Mag";
for "_i" from 1 to 9 do {_this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
_this addBackpack "B_TacticalPack_blk";
for "_i" from 1 to 4 do {_this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 3 do {_this addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 3 do {_this addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 2 do {_this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 3 do {_this addItemToBackpack "ACE_quikclot";};
_this addItemToBackpack "ACE_NVG_Gen2";
_this addItemToBackpack "acc_pointer_IR";
_this addItemToBackpack "muzzle_snds_L";
_this addItemToBackpack "MineDetector";
_this addItemToBackpack "muzzle_snds_M";
for "_i" from 1 to 2 do {_this addItemToBackpack "MiniGrenade";};
for "_i" from 1 to 2 do {_this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 3 do {_this addItemToBackpack "DemoCharge_Remote_Mag";};
_this addItemToBackpack "SatchelCharge_Remote_Mag";
_this addHeadgear "H_Cap_headphones";
_this addGoggles "G_Balaclava_lowprofile";

comment "Add weapons";
_this addWeapon "arifle_Mk20C_plain_F";
_this addPrimaryWeaponItem "acc_flashlight";
_this addPrimaryWeaponItem "optic_Aco";
_this addWeapon "hgun_P07_F";
_this addWeapon "Binocular";
_this addMagazine "30Rnd_556x45_Stanag_Tracer_Red";

comment "Add items";
_this linkItem "ItemMap";
_this linkItem "ItemCompass";
_this linkItem "ItemWatch";
_this linkItem "ItemAndroid";