comment "Exported from Arsenal by IndeedPete";

comment "Remove existing items";
removeAllWeapons _this;
removeAllItems _this;
removeAllAssignedItems _this;
removeUniform _this;
removeVest _this;
removeBackpack _this;
removeHeadgear _this;
removeGoggles _this;

comment "Add containers";
_this forceAddUniform "IP_U_B_CombatUniform_mcam_EFAltis";
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_elasticBandage";};
_this addItemToUniform "ACE_tourniquet";
_this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_IR_Strobe_Item";};
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_CableTie";};
_this addItemToUniform "ACE_EarPlugs";
_this addItemToUniform "Chemlight_green";
_this addItemToUniform "Chemlight_red";
_this addItemToUniform "Chemlight_yellow";
_this addItemToUniform "Chemlight_blue";
_this addItemToUniform "MiniGrenade";
_this addItemToUniform "SmokeShell";
_this addVest "IP_V_PlateCarrierGL_rgrEF";
for "_i" from 1 to 2 do {_this addItemToVest "11Rnd_45ACP_Mag";};
for "_i" from 1 to 5 do {_this addItemToVest "30Rnd_65x39_caseless_mag_Tracer";};
for "_i" from 1 to 4 do {_this addItemToVest "HandGrenade";};
_this addItemToVest "1Rnd_SmokeRed_Grenade_shell";
_this addItemToVest "1Rnd_SmokeGreen_Grenade_shell";
_this addItemToVest "1Rnd_SmokeYellow_Grenade_shell";
_this addItemToVest "1Rnd_SmokePurple_Grenade_shell";
_this addItemToVest "1Rnd_SmokeBlue_Grenade_shell";
_this addItemToVest "1Rnd_SmokeOrange_Grenade_shell";
for "_i" from 1 to 3 do {_this addItemToVest "1Rnd_Smoke_Grenade_shell";};
_this addBackpack "IP_B_AssaultPack_EFAltis";
for "_i" from 1 to 6 do {_this addItemToBackpack "3Rnd_HE_Grenade_shell";};
for "_i" from 1 to 3 do {_this addItemToBackpack "ACE_HuntIR_M203";};
for "_i" from 1 to 3 do {_this addItemToBackpack "B_IR_Grenade";};
for "_i" from 1 to 4 do {_this addItemToBackpack "30Rnd_65x39_caseless_mag_Tracer";};
_this addItemToBackpack "UGL_FlareCIR_F";
_this addItemToBackpack "UGL_FlareRed_F";
_this addHeadgear "IP_H_HelmetSpecB_Green";
_this addGoggles "G_Balaclava_combat";

comment "Add weapons";
_this addWeapon "IP_arifle_MX_GL_Sage_F";
_this addPrimaryWeaponItem "ACE_muzzle_mzls_H";
_this addPrimaryWeaponItem "acc_pointer_IR";
_this addPrimaryWeaponItem "optic_Hamr";
_this addWeapon "hgun_Pistol_heavy_01_F";
_this addHandgunItem "muzzle_snds_acp";
_this addWeapon "Binocular";
_this addMagazine "30Rnd_65x39_caseless_mag_Tracer";
_this addMagazine "3Rnd_HE_Grenade_shell";

comment "Add items";
_this linkItem "ItemMap";
_this linkItem "ItemCompass";
_this linkItem "ItemWatch";
_this linkItem "ItemAndroid";
_this linkItem "NVGoggles";