comment "Exported from Arsenal by IndeedPete";

comment "Remove existing items";
removeAllWeapons _this;
removeAllItems _this;
removeAllAssignedItems _this;
removeUniform _this;
removeVest _this;
removeBackpack _this;
removeHeadgear _this;
removeGoggles _this;

comment "Add containers";
_this forceAddUniform "IP_U_B_CombatUniform_Splinter_Altis";
for "_i" from 1 to 2 do {_this addItemToUniform "30Rnd_65x39_caseless_mag_Tracer";};
for "_i" from 1 to 2 do {_this addItemToUniform "16Rnd_9x21_Mag";};
_this addVest "IP_V_PlateCarrier1_rgrEF";
for "_i" from 1 to 2 do {_this addItemToVest "ACE_CableTie";};
for "_i" from 1 to 7 do {_this addItemToVest "30Rnd_65x39_caseless_mag_Tracer";};
for "_i" from 1 to 5 do {_this addItemToVest "SmokeShell";};
_this addItemToVest "SmokeShellRed";
for "_i" from 1 to 2 do {_this addItemToVest "SmokeShellGreen";};
for "_i" from 1 to 3 do {_this addItemToVest "Chemlight_green";};
for "_i" from 1 to 3 do {_this addItemToVest "Chemlight_red";};
for "_i" from 1 to 3 do {_this addItemToVest "Chemlight_yellow";};
for "_i" from 1 to 3 do {_this addItemToVest "Chemlight_blue";};
_this addItemToVest "16Rnd_9x21_Mag";
_this addBackpack "IP_B_Kitbag_Splinter_Altis";
_this addItemToBackpack "muzzle_snds_H";
_this addItemToBackpack "acc_flashlight";
for "_i" from 1 to 10 do {_this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 20 do {_this addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 15 do {_this addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 8 do {_this addItemToBackpack "ACE_quikclot";};
for "_i" from 1 to 3 do {_this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 9 do {_this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {_this addItemToBackpack "ACE_atropine";};
for "_i" from 1 to 6 do {_this addItemToBackpack "ACE_epinephrine";};
_this addItemToBackpack "ACE_personalAidKit";
_this addItemToBackpack "ACE_surgicalKit";
_this addItemToBackpack "ACE_Flashlight_XL50";
for "_i" from 1 to 5 do {_this addItemToBackpack "ACE_EarPlugs";};
for "_i" from 1 to 4 do {_this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 2 do {_this addItemToBackpack "ACE_CableTie";};
for "_i" from 1 to 4 do {_this addItemToBackpack "ACE_bodyBag";};
for "_i" from 1 to 3 do {_this addItemToBackpack "ACE_IR_Strobe_Item";};
for "_i" from 1 to 2 do {_this addItemToBackpack "ACE_salineIV";};
for "_i" from 1 to 4 do {_this addItemToBackpack "ACE_salineIV_250";};
_this addItemToBackpack "muzzle_snds_L";
for "_i" from 1 to 2 do {_this addItemToBackpack "B_IR_Grenade";};
_this addHeadgear "IP_H_HelmetB_light_Green";

comment "Add weapons";
_this addWeapon "IP_arifle_MX_Sage_F";
_this addPrimaryWeaponItem "acc_pointer_IR";
_this addPrimaryWeaponItem "optic_MRCO";
_this addWeapon "hgun_P07_F";
_this addMagazine "30Rnd_65x39_caseless_mag_Tracer";

comment "Add items";
_this linkItem "ItemMap";
_this linkItem "ItemCompass";
_this linkItem "ItemWatch";
_this linkItem "ItemAndroid";
_this linkItem "NVGoggles_INDEP";

comment "Set identity";
//_this setFace "STAF_WhiteHead_03_ATACS_Lush";
_this setSpeaker "ACE_NoVoice";
[_this,"STAF_Medic"] call bis_fnc_setUnitInsignia;