comment "Exported from Arsenal by IndeedPete";

comment "Remove existing items";
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

comment "Add containers";
this forceAddUniform "IP_U_B_CombatUniform_mcam_EFAltis";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 3 do {this addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 3 do {this addItemToUniform "ACE_elasticBandage";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 3 do {this addItemToUniform "ACE_IR_Strobe_Item";};
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "Chemlight_green";
this addItemToUniform "Chemlight_red";
this addItemToUniform "Chemlight_yellow";
this addItemToUniform "Chemlight_blue";
for "_i" from 1 to 2 do {this addItemToUniform "MiniGrenade";};
this addVest "IP_V_TacVest_EFAltis";
this addItemToVest "ACE_morphine";
this addItemToVest "ACE_elasticBandage";
this addItemToVest "ACE_packingBandage";
this addItemToVest "ACE_fieldDressing";
this addItemToVest "ACE_quikclot";
this addItemToVest "tf_anprc152_2";
for "_i" from 1 to 2 do {this addItemToVest "16Rnd_9x21_Mag";};
for "_i" from 1 to 5 do {this addItemToVest "30Rnd_65x39_caseless_mag_Tracer";};
this addItemToVest "SmokeShell";
this addItemToVest "SmokeShellYellow";
this addItemToVest "SmokeShellRed";
this addItemToVest "SmokeShellGreen";
this addItemToVest "SmokeShellPurple";
this addItemToVest "SmokeShellBlue";
this addBackpack "STAF_tf_anarc210_Sage";
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_CableTie";};
this addItemToBackpack "SmokeShellOrange";
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
this addHeadgear "IP_H_MilCap_mcamoEFAltis";

comment "Add weapons";
this addWeapon "IP_arifle_MXC_Sage_F";
this addPrimaryWeaponItem "ACE_muzzle_mzls_H";
this addPrimaryWeaponItem "acc_pointer_IR";
this addPrimaryWeaponItem "optic_Aco";
this addWeapon "hgun_P07_F";
this addWeapon "Rangefinder";

comment "Add items";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemcTab";
this linkItem "NVGoggles";