comment "Exported from Arsenal by IndeedPete";

comment "Remove existing items";
removeAllWeapons _this;
removeAllItems _this;
removeAllAssignedItems _this;
removeUniform _this;
removeVest _this;
removeBackpack _this;
removeHeadgear _this;
removeGoggles _this;

comment "Add containers";
_this forceAddUniform "IP_U_B_CombatUniform_Flecktarn_Altis_Wolf_vest";
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_elasticBandage";};
_this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_morphine";};
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_quikclot";};
_this addItemToUniform "ACE_EarPlugs";
_this addItemToUniform "ACE_IR_Strobe_Item";
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_CableTie";};
_this addItemToUniform "Chemlight_green";
_this addItemToUniform "Chemlight_red";
_this addItemToUniform "Chemlight_yellow";
_this addItemToUniform "Chemlight_blue";
for "_i" from 1 to 2 do {_this addItemToUniform "16Rnd_9x21_Mag";};
_this addVest "IP_V_PlateCarrier1_altisEFWolf";
for "_i" from 1 to 2 do {_this addItemToVest "ACE_IR_Strobe_Item";};
for "_i" from 1 to 2 do {_this addItemToVest "HandGrenade";};
for "_i" from 1 to 3 do {_this addItemToVest "SmokeShell";};
_this addItemToVest "SmokeShellYellow";
_this addItemToVest "SmokeShellRed";
_this addItemToVest "SmokeShellGreen";
_this addItemToVest "SmokeShellPurple";
_this addItemToVest "SmokeShellBlue";
_this addItemToVest "SmokeShellOrange";
for "_i" from 1 to 2 do {_this addItemToVest "B_IR_Grenade";};
for "_i" from 1 to 2 do {_this addItemToVest "MiniGrenade";};
_this addItemToVest "200Rnd_65x39_cased_Box_Tracer";
_this addBackpack "IP_B_Kitbag_Splinter_Altis";
_this addItemToBackpack "ACE_SpareBarrel";
_this addItemToBackpack "ACE_personalAidKit";
for "_i" from 1 to 5 do {_this addItemToBackpack "200Rnd_65x39_cased_Box_Tracer";};
_this addHeadgear "IP_H_HelmetB_Altis";
_this addGoggles "G_Combat";

comment "Add weapons";
_this addWeapon "LMG_Mk200_F";
_this addPrimaryWeaponItem "ACE_muzzle_mzls_H";
_this addPrimaryWeaponItem "acc_pointer_IR";
_this addPrimaryWeaponItem "optic_Hamr";
_this addPrimaryWeaponItem "bipod_01_F_blk";
_this addWeapon "hgun_P07_F";
_this addHandgunItem "muzzle_snds_L";
_this addWeapon "Binocular";
_this addMagazine "200Rnd_65x39_cased_Box_Tracer";

comment "Add items";
_this linkItem "ItemMap";
_this linkItem "ItemCompass";
_this linkItem "ItemWatch";
_this linkItem "ItemAndroid";
_this linkItem "NVGoggles";

comment "Set identity";
//_this setFace "AfricanHead_03";
_this setSpeaker "ACE_NoVoice";