_target = sideUnknown;
_restrictionDistance = 5;
_specNames = ["Recon TL", "Recon Marksman", "Recon FO / Radio Operator", "Medic", "Recon Scount (AT)", "Recon Explosive Specialist", "Sentry Killer", "Recon Scout", "Recon Spotter", "Recon Sniper", "Helicopter Pilot", "Drone Operator"];
_specSlots = [1e100, 1e100, 1e100, 1e100, 1e100, 1e100, 1e100, 1e100, 1e100, 1e100, 1e100, 1e100];
_specTypes = [
	["IP_I_PMC_Tropic_Recon_TL_F"],
	["IP_I_PMC_Tropic_Recon_M_F"],
	["IP_I_PMC_Tropic_Recon_FO_F"],
	["IP_I_PMC_Tropic_Recon_Medic_F"],
	["IP_I_PMC_Tropic_Recon_LAT_F"],
	["IP_I_PMC_Tropic_Recon_Exp_F"],
	["IP_I_PMC_Tropic_Sentry_Killer_F"],
	["IP_I_PMC_Tropic_Recon_F"],
	["IP_I_PMC_Tropic_Recon_Spotter_F"],
	["IP_I_PMC_Tropic_Sniper_F"],
	["IP_I_PMC_Tropic_Heli_Pilot_F"],
	["IP_I_PMC_Tropic_Recon_UAV_F"]
];
_useXLA = true;

_basicItems = [
	"hgun_Rook40_F",
	"16Rnd_9x21_Mag",
	"30Rnd_65x39_caseless_mag",
	"30Rnd_65x39_caseless_mag_Tracer",
	"20Rnd_762x51_Mag",
	"10Rnd_93x64_DMR_05_Mag",
	"10Rnd_127x54_Mag",
	"7Rnd_408_Mag",
	"hlc_20Rnd_762x51_B_M14",
	"hlc_20Rnd_762x51_S_M14",
	"hlc_20Rnd_762x51_T_M14",
	"hlc_muzzle_snds_M14",
	"1Rnd_HE_Grenade_shell",
	"UGL_FlareWhite_F",
	"UGL_FlareGreen_F",
	"UGL_FlareRed_F",
	"UGL_FlareYellow_F",
	"UGL_FlareCIR_F",
	"1Rnd_Smoke_Grenade_shell",
	"1Rnd_SmokeRed_Grenade_shell",
	"1Rnd_SmokeGreen_Grenade_shell",
	"1Rnd_SmokeYellow_Grenade_shell",
	"1Rnd_SmokePurple_Grenade_shell",
	"1Rnd_SmokeBlue_Grenade_shell",
	"1Rnd_SmokeOrange_Grenade_shell",
	"3Rnd_HE_Grenade_shell",
	"3Rnd_UGL_FlareWhite_F",
	"3Rnd_UGL_FlareGreen_F",
	"3Rnd_UGL_FlareRed_F",
	"3Rnd_UGL_FlareYellow_F",
	"3Rnd_UGL_FlareCIR_F",
	"3Rnd_Smoke_Grenade_shell",
	"3Rnd_SmokeRed_Grenade_shell",
	"3Rnd_SmokeGreen_Grenade_shell",
	"3Rnd_SmokeYellow_Grenade_shell",
	"3Rnd_SmokePurple_Grenade_shell",
	"3Rnd_SmokeBlue_Grenade_shell",
	"3Rnd_SmokeOrange_Grenade_shell",
	"30Rnd_556x45_Stanag",
	"30Rnd_556x45_Stanag_Tracer_Red",
	"30Rnd_556x45_Stanag_Tracer_Green",
	"30Rnd_556x45_Stanag_Tracer_Yellow",
	"hlc_100Rnd_762x51_M_M60E4",
	"150Rnd_93x64_Mag",
	"NLAW_F",
	"Titan_AT",
	"Titan_AP",
	"HandGrenade",
	"MiniGrenade",
	"SmokeShell",
	"SmokeShellYellow",
	"SmokeShellGreen",
	"SmokeShellRed",
	"SmokeShellPurple",
	"SmokeShellOrange",
	"SmokeShellBlue",
	"Chemlight_green",
	"Chemlight_red",
	"Chemlight_yellow",
	"Chemlight_blue",
	"I_IR_Grenade",
	"Laserbatteries",
	"muzzle_snds_H",
	"muzzle_snds_L",
	"muzzle_snds_M",
	"muzzle_snds_B",
	"muzzle_snds_acp",
	"muzzle_snds_H_MG",
	"muzzle_snds_H_SW",
	"muzzle_snds_338_black",
	"muzzle_snds_338_green",
	"muzzle_snds_338_sand",
	"muzzle_snds_93mmg",
	"muzzle_snds_93mmg_tan",	
	"optic_Aco",	
	"bipod_01_F_blk",
	"acc_flashlight",
	"acc_pointer_IR",
	"ItemWatch",
	"ItemRadio",
	"ItemMap",
	"ItemCompass",
	"ItemGPS",
	"h_Beret_grn",
	"H_Beret_grn_SF",
	"G_Balaclava_blk",
	"G_Balaclava_combat",
	"G_Balaclava_lowprofile",
	"G_Balaclava_oli",
	"G_Bandanna_aviator",
	"G_Bandanna_beast",
	"G_Bandanna_blk",
	"G_Bandanna_khk",
	"G_Bandanna_oli",
	"G_Bandanna_shades",
	"G_Bandanna_sport",
	"G_Bandanna_tan",
	"G_Combat",
	"G_Lowprofile",
	"G_Tactical_Black",
	"G_Tactical_Clear",
	"G_Aviator",
	"G_Spectacles",
	"G_Spectacles_Tinted",
	"G_Squares",
	"G_Squares_Tinted",
	"G_Shades_Black",
	"G_Shades_Blue",
	"G_Shades_Green",
	"G_Shades_Red",
	"G_Sport_Blackred",
	"G_Sport_BlackWhite",
	"G_Sport_Blackyellow",
	"G_Sport_Checkered",
	"G_Sport_Greenblack",
	"G_Sport_Red",
	"G_Lady_Blue",
	"G_Lady_Dark",
	"G_Lady_Mirror",
	"G_Lady_Red",
	"STAF_G_Bandanna_Punisher",
	// ACE3
	"ACE_IR_Strobe_Item",
	"ACE_CableTie",
	"ACE_muzzle_mzls_H",
	"ACE_muzzle_mzls_B",
	"ACE_muzzle_mzls_L",
	"ACE_muzzle_mzls_smg_01",
	"ACE_muzzle_mzls_smg_02",
	"ACE_muzzle_mzls_338",
	"ACE_muzzle_mzls_93mmg",
	"ACE_HandFlare_WhiteMuzzle",
	"ACE_HandFlare_RedMuzzle",
	"ACE_HandFlare_GreenMuzzle",
	"ACE_HandFlare_YellowMuzzle",
	"ACE_M84Muzzle",
	"ACE_EarPlugs",
	"ACE_acc_pointer_red",
	"ACE_acc_pointer_green_IR",
	"ACE_acc_pointer_green",
	"ACE_wirecutter",
	"ACE_fieldDressing",
	"ACE_packingBandage",
	"ACE_elasticBandage",
	"ACE_tourniquet",
	"ACE_morphine",
	"ACE_quikclot",
	"ACE_personalAidKit",
	/*
	"ACE_NVG_Gen1",
	"ACE_NVG_Gen2",
	"ACE_NVG_Gen3",
	"ACE_NVG_Gen4",
	"ACE_NVG_Wide",
	*/
	"ACE_DAGR",
	"ACE_RangeTable_82mm",
	/*
	"ACE_optic_Arco_2D",
	"ACE_optic_Arco_PIP",
	*/
	"ACE_Altimeter",
	/*
	"ACE_LMG_coax_MBT_01",
	"ACE_LMG_coax_APC_Tracked_03",
	*/
	"ACE_acc_flashlight_tls",
	"ACE_20Rnd_762x51_Mag_Tracer",
	"ACE_20Rnd_762x51_Mag_Tracer_Dim",
	"ACE_20Rnd_762x51_Mk316_Mod_0_Mag",
	"ACE_20Rnd_762x51_M118LR_Mag",
	"ACE_20Rnd_762x51_Mk319_Mod_0_Mag",
	"ACE_20Rnd_762x51_M993_AP_Mag",
	"ACE_20Rnd_762x51_Mag_SD",
	"ACE_20Rnd_762x67_Berger_Hybrid_OTM_Mag",
	"ACE_20Rnd_762x67_Mk248_Mod_0_Mag",
	"ACE_20Rnd_762x67_Mk248_Mod_0_Mag",
	"ACE_10Rnd_338_API528_Mag",
	"ACE_10Rnd_338_300gr_HPBT_Mag",
	"ACE_10Rnd_338_API526_Mag",
	"ACE_20Rnd_762x67_Mk248_Mod_1_Mag",
	"ACE_30Rnd_65x39_caseless_mag_Tracer_Dim",
	"ACE_30Rnd_65x47_Scenar_mag",
	"ACE_30Rnd_65_Creedmor_mag",
	"ACE_30Rnd_556x45_Stanag_M995_AP_mag",
	"ACE_30Rnd_556x45_Stanag_Mk262_mag",
	"ACE_30Rnd_556x45_Stanag_Mk318_mag",
	"ACE_30Rnd_556x45_Stanag_Tracer_Dim",
	"ACE_200Rnd_65x39_cased_Box_Tracer_Dim",
	"ACE_Flashlight_MX991",
	"ACE_Flashlight_KSF1",
	"ACE_Flashlight_XL50",
	"ACE_Tripod",
	"ACE_MapTools",
	//Task Force Arrowhead
	/*"tf_anprc152",
	"tf_anprc152_2",
	"tf_anprc152_3",
	"tf_anprc152_4",
	"tf_anprc152_5",
	"tf_anprc152_6",
	"tf_anprc152_7",
	"tf_anprc152_8",
	"tf_anprc152_9",
	"tf_anprc152_10",
	"tf_anprc152_11",
	"tf_anprc152_12",
	"tf_anprc152_13",
	"tf_anprc152_14",
	"tf_anprc152_15",
	"tf_anprc152_16",
	"tf_anprc152_17",
	"tf_anprc152_18",
	"tf_anprc152_19",
	"tf_anprc152_20",
	"tf_rf7800str",
	"tf_rt1523g",
	"tf_rt1523g_big",
	"tf_rt1523g_black",
	"tf_rt1523g_fabric",
	"tf_rt1523g_green",
	"tf_rt1523g_rhs",
	"tf_rt1523g_sage",
	"tf_rt1523g_big_bwmod",
	"tf_rt1523g_big_bwmod_tropen",
	"tf_rt1523g_big_bwmod_flecken",
	//"tf_anprc152_2",
	"tf_rf7800str_2",
	"tf_rt1523g_2",
	"tf_rt1523g_big_2",
	"tf_rt1523g_black_2",
	"tf_rt1523g_fabric_2",
	"tf_rt1523g_green_2",
	"tf_rt1523g_rhs_2",
	"tf_rt1523g_sage_2",*/
	"tf_anprc154",
	"tf_anprc148jem",
	
	// PMC Tropic Start
	"IP_H_Booniehat_MCAM_Tropic",
	"IP_H_MilCap_MCAM_Tropic",
	"IP_V_TacVest_MCAM_Tropic",
	"IP_NVGoggles_Tropic",
	"IP_H_Cap_MCAM_Tropic",
	"IP_H_Cap_HS_MCAM_Tropic",
	"IP_H_Booniehat_HS_MCAM_Tropic",
	"IP_H_Bandanna_MCAM_Tropic",
	"IP_H_Bandanna_HS_MCAM_Tropic",
	"IP_U_I_CombatUniform_light_olive",
	"IP_U_I_CombatUniform_light_olive_shortsleeve",
	"IP_H_Cap_headphones_MCAM_Tropic",
	"IP_I_AssaultPack_MCAM_Tropic",
	// PMC Tropic End
	
	"EF_2ndServMedic",
	"EF_2ndServTech",
	"EF_1stServ",
	"EF_1stServMedic",
	"EF_1stServTech",
	"EF_ServChief",
	"EF_ServChiefMedic",
	"EF_ServChiefTech",
	"EF_GyChief",
	"EF_GyChiefMedic",
	"EF_GyChiefTech",
	"EF_OpChief",
	"EF_OpChiefMedic",
	"EF_OpChiefTech",
	"EF_Lt",
	"EF_LtMedic",
	"EF_LtTech",
	"EF_LtCdr",
	"EF_LtCdrMedic",
	"EF_LtCdrTech",
	"EF_Cdr",
	"EF_CdrMedic",
	"EF_CdrTech",
	"EF_Cpt",
	"EF_CptMedic",
	"EF_CptTech",
	"EF_Albania",
	"EF_Austria",
	"EF_Belgium",
	"EF_Bosnia_And_Herzegovina",
	"EF_Bulgaria",
	"EF_Croatia",
	"EF_Cyprus",
	"EF_Czech_Republic",
	"EF_Denmark",
	"EF_England",
	"EF_Estonia",
	"EF_Finland",
	"EF_France",
	"EF_FYROM",
	"EF_Germany",
	"EF_Greece",
	"EF_Hungary",
	"EF_Iceland",
	"EF_Ireland",
	"EF_Italy",
	"EF_Latvia",
	"EF_Lithuania",
	"EF_Luxembourg",
	"EF_Malta",
	"EF_Montenegro",
	"EF_Netherlands",
	"EF_Norway",
	"EF_Poland",
	"EF_Portugal",
	"EF_Romania",
	"EF_Scotland",
	"EF_Serbia",
	"EF_Slovakia",
	"EF_Slovenia",
	"EF_Spain",
	"EF_Sweden",
	"EF_United_Kingdom",
	"EF_Wales",
	"STAF_Medic",
	//MCC
	"MCC_videoProbe",
	"MCC_multiTool",
	//cTab
	"ItemAndroid",
	"ItemcTabHCam"
];

_reconItems = [
	"IP_U_I_CombatUniform_MCAM_Tropic",
	"IP_U_I_CombatUniform_MCAM_Tropic_vest",
	"Binocular"
] + _basicItems;

_TLItems = [
	"IP_V_PlateCarrierIA1_MCAM_Tropic",
	"IP_V_PlateCarrierIA2_MCAM_Tropic",
	"hlc_rifle_G36KMLIC",
	"hlc_rifle_G36CMLIC",
	"hlc_rifle_m14sopmod",
	"IP_arifle_Mk20C_mcam_tropic_F",
	"IP_arifle_Mk20_mcam_tropic_F",
	"Rangefinder",
	"ACE_microDAGR",
	"ACE_HuntIR_monitor",
	"ACE_HuntIR_M203",
	"ACE_Vector",
	"ItemcTab",
	"optic_Hamr",
	"optic_MRCO",
	"ACE_optic_Hamr_2D",
	"ACE_optic_Hamr_PIP",
	"ACE_optic_MRCO_2D",
	"ACE_optic_MRCO_PIP"
] + _reconItems;

_marksmanItems = [
	"hlc_rifle_m14sopmod",
	"IP_srifle_DMR_03_MCAM_Tropic_F",
	"optic_NVS",
	"optic_Nightstalker",
	"optic_tws",
	"optic_DMS",
	"optic_AMS",
	"optic_Hamr",
	"optic_MRCO",
	"Rangefinder",
	"ACE_ATragMX",
	"ACE_microDAGR",
	"ACE_Vector",
	"ACE_Kestrel4500",
	"ACE_SpottingScope",
	"ACE_RangeCard"
] + _reconItems;

_FOItems = [
	"IP_V_PlateCarrierIA1_MCAM_Tropic",
	"IP_arifle_Mk20C_mcam_tropic_F",
	"IP_arifle_Mk20_mcam_tropic_F",
	"IP_arifle_Mk20_GL_mcam_tropic_F",
	"Laserdesignator",
	"ACE_microDAGR",
	"ACE_HuntIR_monitor",
	"ACE_HuntIR_M203",
	"optic_MRCO",
	"IP_tf_anprc155_mcam_tropic",
	"IP_tf_anarc164_mcam_tropic"
] + _reconItems;

_medicItems = [
	"IP_arifle_Mk20C_mcam_tropic_F",
	"ACE_atropine",
	"ACE_epinephrine",
	"ACE_plasmaIV",
	"ACE_plasmaIV_500",
	"ACE_plasmaIV_250",
	"ACE_bloodIV",
	"ACE_bloodIV_500",
	"ACE_bloodIV_250",
	"ACE_salineIV",
	"ACE_salineIV_500",
	"ACE_salineIV_250",
	"ACE_surgicalKit",
	"ACE_bodyBag",
	"IP_I_AssaultPack_MCAM_Tropic_Medic",
	//"IP_I_Kitbag_MCAM_Tropic_Medic",
	"IP_H_HelmetIA_MCAM_Tropic",
	"IP_V_PlateCarrierIA1_MCAM_Tropic",
	"IP_V_PlateCarrierIA2_MCAM_Tropic"
] + _reconItems;

_latItems = [
	"hlc_rifle_G36CMLIC",
	"IP_arifle_Mk20C_mcam_tropic_F",
	"IP_arifle_Mk20_mcam_tropic_F",
	"launch_NLAW_F"
] + _reconItems;

_expItems = [
	"IP_arifle_Mk20C_mcam_tropic_F",
	"IP_I_Kitbag_MCAM_Tropic",
	"IP_V_PlateCarrierIA1_MCAM_Tropic",
	"IP_V_PlateCarrierIA2_MCAM_Tropic",
	"DemoCharge_Remote_Mag",
	"SatchelCharge_Remote_Mag",
	"ATMine_Range_Mag",
	"ClaymoreDirectionalMine_Remote_Mag",
	"APERSMine_Range_Mag",
	"APERSBoundingMine_Range_Mag",
	"SLAMDirectionalMine_Wire_Mag",
	"APERSTripMine_Wire_Mag",
	"ACE_Clacker",
	"ACE_M26_Clacker",
	"ACE_DefusalKit",
	"ACE_DeadManSwitch",
	"ACE_Cellphone",
	"ToolKit",
	"MineDetector"
] + _reconItems;

_sniperItems = [
	"hlc_rifle_m14sopmod",
	"IP_srifle_DMR_03_MCAM_Tropic_F",
	"IP_srifle_DMR_05_MCAM_Tropic_F",
	"optic_NVS",
	"optic_Nightstalker",
	"optic_tws",
	"optic_DMS",
	"optic_AMS",
	"optic_Hamr",
	"optic_MRCO",
	"Rangefinder",
	"ACE_ATragMX",
	"ACE_microDAGR",
	"ACE_Vector",
	"ACE_Kestrel4500",
	"ACE_SpottingScope",
	"ACE_RangeCard",
	"srifle_LRR_F",	
	"optic_LRPS",
	"optic_KHS_blk",
	"ACE_optic_LRPS_2D",
	"ACE_optic_LRPS_PIP"
] + _reconItems;

_spotterItems = [
	"IP_arifle_Mk20C_mcam_tropic_F",
	"Laserdesignator",
	"ACE_ATragMX",
	"ACE_microDAGR",
	"ACE_Vector",
	"ACE_Kestrel4500",
	"ACE_SpottingScope",
	"ACE_RangeCard"
] + _reconItems;

_pilotItems = [
	"IP_arifle_Mk20C_mcam_tropic_F",
	"IP_tf_anarc164_mcam_tropic"
] + _basicItems;

_scoutItems = [
	"hlc_rifle_G36KMLIC",
	"hlc_rifle_G36CMLIC",
	"hlc_rifle_m14sopmod",
	"IP_arifle_Mk20C_mcam_tropic_F",
	"IP_arifle_Mk20_mcam_tropic_F",
	"optic_Hamr",
	"optic_MRCO"
] + _reconItems;

_sentryKillerItems = [
	"hlc_rifle_m14sopmod",
	"IP_srifle_DMR_04_MCAM_Tropic_F",
	"optic_NVS",
	"optic_Nightstalker",
	"optic_tws",
	"optic_Hamr",
	"optic_MRCO",
	"IP_V_HarnessO_MCAM_Tropic"
] + _reconItems;

_UAVItems = [
	"IP_arifle_Mk20C_mcam_tropic_F",
	"I_UavTerminal",
	"IP_I_UAV_01_backpack_MCAM_Tropic_F"
] + _reconItems;

_specItems = [_TLItems, _marksmanItems, _FOItems, _medicItems, _latItems, _expItems, _sentryKillerItems, _scoutItems, _spotterItems, _sniperItems, _pilotItems, _UAVItems];

//////////////////////////////////////////////////////////////////////////////////////////////

[_target, [ObjNull, _restrictionDistance, _specNames, _specSlots, _specTypes, _specItems, _useXLA]]