removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;

player forceAddUniform "U_B_FullGhillie_lsh";
for "_i" from 1 to 2 do {player addItemToUniform "11Rnd_45ACP_Mag";};
for "_i" from 1 to 3 do {player addItemToUniform "10Rnd_338_Mag";};
player addVest "IP_V_PlateCarrier1_rgrEF";
for "_i" from 1 to 3 do {player addItemToVest "ACE_elasticBandage";};
player addItemToVest "ACE_EarPlugs";
player addItemToVest "ACE_epinephrine";
player addItemToVest "ACE_IR_Strobe_Item";
player addItemToVest "ACE_MapTools";
player addItemToVest "ACE_morphine";
player addItemToVest "ACE_Flashlight_XL50";
for "_i" from 1 to 3 do {player addItemToVest "ACE_packingBandage";};
player addItemToVest "ACE_personalAidKit";
player addItemToVest "ACE_tourniquet";
player addItemToVest "ACE_ATragMX";
player addItemToVest "ACE_DAGR";
player addItemToVest "11Rnd_45ACP_Mag";
for "_i" from 1 to 2 do {player addItemToVest "10Rnd_338_Mag";};
for "_i" from 1 to 2 do {player addItemToVest "ACE_10Rnd_338_300gr_HPBT_Mag";};
for "_i" from 1 to 3 do {player addItemToVest "ACE_10Rnd_338_API526_Mag";};
player addBackpack "B_Kitbag_rgr";
player addItemToBackpack "ACE_Clacker";
player addItemToBackpack "ACE_Kestrel4500";
Player addItemToBackpack "ACE_ATragMX";
player addItemToBackpack "SMG_02_F";
for "_i" from 1 to 3 do {player addItemToBackpack "ClaymoreDirectionalMine_Remote_Mag";};
for "_i" from 1 to 3 do {player addItemToBackpack "30Rnd_9x21_Mag_SMG_02";};
player addItemToBackpack "30Rnd_65x39_caseless_mag";
for "_i" from 1 to 4 do {player addItemToBackpack "10Rnd_338_Mag";};
player addHeadgear "IP_H_HelmetSpecB_Green";

player addWeapon "srifle_DMR_02_camo_F";
player addPrimaryWeaponItem "muzzle_snds_338_black";
player addPrimaryWeaponItem "acc_pointer_IR";
player addPrimaryWeaponItem "optic_LRPS";
player addPrimaryWeaponItem "bipod_01_F_blk";
player addWeapon "hgun_Pistol_heavy_01_F";

player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "tf_anprc152_6";
player linkItem "ItemAndroid";
player linkItem "NVGoggles_INDEP";
